### ISSUE TITLE
Remove some or all of the example test cases from API projects

### ISSUE THREAD

**Issue by MikeTheCanuck** [hackoregon/civic-devops#169] opened 2018-06-09 23:25 UTC
Disaster Resilience ran into a problem during Travis build that was traced to one of the example test cases that apparently requires write access to "reset the database":
https://github.com/hackoregon/disaster-resilience-backend/pull/22

We should eliminate this test case from all the backend projects (and if they have at least one working, non-example test case, we can remove all the examples - which were only introduced to support the `pytest` testing approach, which will fail in Travis builds if there are no tests available to run):
- [x] [disaster-resilience-backend](https://github.com/hackoregon/disaster-resilience-backend)
- [x] [elections-2018-backend](https://github.com/hackoregon/elections-2018-backend)
- [x] [housing-2018](https://github.com/hackoregon/housing-2018)
- [ ] [neighborhoods-2018](https://github.com/hackoregon/neighborhoods-2018)
- [ ] [transportation-systems-backend-2018](https://github.com/hackoregon/transportation-systems-backend-2018)

**Comment by MikeTheCanuck** [comment] 2018-07-08 04:08
## Results of Analysis
- [ ] [disaster-resilience-backend](https://github.com/hackoregon/disaster-resilience-backend) - has one smoke test for the route `/disaster-resilience/` and three dummy "pass" tests still
- [ ] [elections-2018-backend](https://github.com/hackoregon/elections-2018-backend) - has one smoke test for the route `/local-elections/` and nothing else
- [ ] [housing-2018](https://github.com/hackoregon/housing-2018) - has a set of basic route-testing tests
- [ ] [neighborhoods-2018](https://github.com/hackoregon/neighborhoods-2018) - has one smoke test for the route `/neighborhood-development/` and three dummy "pass" tests still
- [ ] [transportation-systems-backend-2018](https://github.com/hackoregon/transportation-systems-backend-2018) - has a set of basic route-testing tests

**Comment by nam20485** [comment] 2018-07-08 20:57
@MikeTheCanuck Please see https://github.com/hackoregon/disaster-resilience-backend/pull/22#issuecomment-396411774. The offending TransactionTestCase in disaster-resilience-backend appearing to need write access to the DB is a red herring, it does not need write access and completes successfully without write access. The problem being reported during the unit tests run is only because a model was changed and merged in *without* new migrations being added after. If the Django migrate command is run and resulting migration files are checked in when the model updates are added, the test case functions correctly with only read-only DB access. See hackoregon/disaster-resilience-backend#20, comment https://github.com/hackoregon/disaster-resilience-backend/pull/20#issuecomment-396410771 for full explanation.

**Comment by MikeTheCanuck** [comment] 2018-07-14 18:09
@nam20485 does this mean that you intend to keep the dummy tests in the repo?  Or are you narrowly responding to the confusion over whether there's a real bug there?  I don't see the value in the dummy tests - they aren't accomplishing anything meaningful, and aren't even necessary once there's at least one functional test that pytest can execute successfully.

**Comment by nam20485** [comment] 2018-07-22 20:30
Narrowly responding to your belief that the dummy test case requires write access and thereby caused an error or bug.

The error was real but was caused by not creating migrations after modifying a model. This is resolved now (and the dummy test cases do not require write access).

As for leaving in the test cases, they do have nominal value in that they catch, as in this case, when the service would fail to start. However I do agree they need to be replaced by real test cases and then removed.

**Comment by nam20485** [comment] 2018-08-05 19:01
@MikeTheCanuck FYI-  I removed the dummy example tests and replaced them with specific endpoint response unit test cases. See https://github.com/hackoregon/disaster-resilience-backend/blob/development/api/tests/tests.py.

It tests that each API endpoint responds with an HTTP 200 response. I plan on adding model and serialization unit test cases, but I think this is a good start to at least ensure the image that is about to be deployed responds correctly. Might be a good example to deploy the rest of the backends. 

@znmeb @BrianHGrant

**Closed** 2019-03-24 19:32 UTC
Labels: Priority: low, good first issue
