### ISSUE TITLE
Automate ecs CF template to use latest ecs optimized AMI

### ISSUE THREAD

**Issue by iant01** [hackoregon/civic-devops#173] opened 2018-06-13 00:55 UTC
AWS is now placing the ID of the latest ecs AMI image into ssm parameter store so that its easier to update bt having scripts/templates check there to get their AMI ID rather than hard coding it in.

Using that setup, the block of code that maps the AMI ID for each region can be removed as it will get the proper image for which ever region it is running in.

With this setup, the next time a stack change set is run after AWS rolls out a new AMI for ecs, the ecs instances will be upgraded to the new image buy the autoscaler as the autoscaler launch configuration will get updated with the latest AMI image ID.

**Comment by MikeTheCanuck** [comment] 2019-06-01 21:08
Looks like current Mike finally considered this a priority despite past Mike's lack of understanding (or due to current issues getting a new copy of the infrastructure stable).  Thanks Ian!

Closing this issue now as a duplicate of https://github.com/hackoregon/hackoregon-aws-infrastructure/issues/64

**Closed by MikeTheCanuck** 2019-06-01 21:08 UTC
Labels: Priority: low
