### ISSUE TITLE
S3 Bucket request for Transportation raw "congestion" dataset

### ISSUE THREAD

**Issue by znmeb** [hackoregon/civic-devops#14] opened 2018-02-15 22:53 UTC
This is our first big dataset and it will be getting bigger. Currently the raw data file is a `.rar` archive that takes up about 4.3 GB compressed and unpacks to 24 GB, most of which is CSV files we need to input into a PostgreSQL database. We expect a new dump every quarter of about the same size.

I'm currently building the ingestion process - see <https://github.com/hackoregon/transportation-congestion-analysis/tree/master/src/data> for the code. My workstation has the capacity to do this, but the end goal is a fully automated AWS process, either containerized. or in a full VM if it's too big for containers. I will be attempting the containerized solution first as I build the processing for this first dataset.

Ideally we'd want to store both the compressed and uncompressed data now, but once it's containerized we can live with just the compressed data file.

**Comment by znmeb** [comment] 2018-02-21 05:23
I have some solid data on the size of the current dataset. I don't have a model to forecast growth over time, so for now I'm assuming we'll get an equivalent size every calendar quarter. The quarters are on an odd cycle.

It looks like TriMet's year starts in September. The first dump we have covers September, October and November 2017. So I'm assuming there will be another dataset available some time in March covering December 2017 and January and February of 2018.

Here's the sizing info: https://github.com/hackoregon/transportation-congestion-analysis/blob/master/src/data/README.md. If we stick to the Cookiecutter Data Science workflow the input `.rar`, all the `.csv` files and any of the database `.backup` files we use in our analysis will be synced to S3,

However, I'm assuming that once our platform is up and running in AWS, raw data and interim data can be archived in "Glacier" rather than having to be live in S3. I'd expect only the most recent quarter to be live, and if we can get monthly datasets from TriMet rather than quarterly, that will make things a lot less strenuous.

**Comment by MikeTheCanuck** [comment] 2018-02-22 23:42
Hi @znmeb, can you give us a little context:
- how many different types of data will be coming in?
- Are you expecting a separate bucket for other non-congestion data?
- Is there any of the data that will have to be separately permissioned (e.g. some data available to anyone on the Internet, some data only available to Hack Oregon, some data only available to Transportation-Systems team members)?

We're going to finalize our proposed S3 storage strategy tonight and these details will help us ensure we're designing for the real world.

**Comment by znmeb** [comment] 2018-02-23 00:05
1. I don't think there is a need for multiple buckets - all the files, database and tables have unique names.
2. I think permissions should be Hack Oregon only for now - the APIs are how we plan to distribute data.

**Comment by bhgrant8** [comment] 2018-02-23 00:18
I agree. Ultimately, we are not looking at "private" data per se, we just want to focus access and distribution through the API, as its intent. 

Permissions are more to serve that goal, and keep down costs.  We don't want the public just coming and downloading the raw data dumps. 

Our conceptualization of Civic as a platform has been that our own data scientists and teams should be working through apis as much as feasible as well.

As such I see the requirements of this to be:
1. backup/archival purposes
2. distribution to database developers to process and turn into a database.

Again we can only speak for transportation systems and not other team workflows, but the benefits of this flow would be less distribution costs and more reproducibility then having multiple people working from the raw csvs.

I'll note here but seems to be clear that Raw data s3 buckets and distribution should be separate from the question of the postgres ingestion into aws. i think this is clear but want to make sure.

**Comment by znmeb** [comment] 2018-02-23 00:46
I'll add that in the case of the TriMet congestion data, the raw input is only about 4 GB for the three months. The ingestion into PostgreSQL is lengthy - it runs about 20 minutes on my 4 GHz workstation - but only needs to be done once per dataset and can be totally automatic on Linux.

**Comment by znmeb** [comment] 2018-03-05 07:00
Check with @bhgrant8 to be sure, but I think we lowered the priority of this dataset.

**Comment by bhgrant8** [comment] 2018-03-07 16:33
@MikeTheCanuck, @znmeb is correct we have lowered the priority of this dataset at this time. That being said, worked with @DingoEatingFuzz to get my aws creds worked out last night and have been able to upload the .rar archive provide for archival purposes. Think we can close this issue. Thanks!

**Comment by DingoEatingFuzz** [comment] 2018-03-07 18:23
Happy to hear it! I love closing issues!

**Closed by DingoEatingFuzz** 2018-03-07 18:23 UTC
Labels: Priority: high
